'use client';

import React, { useEffect, useState } from 'react';
import ProtectedRoute from '@/components/ProtectedRoute';
import { useSelector } from 'react-redux';
import { RootState } from '@/redux/store';
import Link from 'next/link';
import api from '@/lib/axiosInstance';

function PlansContent({ user }: { user: any }) {
  const [activeTab, setActiveTab] = useState<'workout' | 'diet'>('workout');
  const [plan, setPlan] = useState<any | null>(null);
  const [blocked, setBlocked] = useState(false);
  const [blockedReason, setBlockedReason] = useState('');
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [expandedDays, setExpandedDays] = useState<Record<string, boolean>>({});

  const fetchPlan = async () => {
    setLoading(true);
    setErrorMsg(null);
    try {
      const res = await api.get('/plans');
      if (res.data.success && res.data.data) {
        setPlan(res.data.data);
      }
    } catch (err: any) {
      setErrorMsg(err.response?.data?.message || 'Failed to load fitness plan.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const hasMedicalRisk =
      (user.medicalConditions?.filter((c: string) => c.trim()).length ?? 0) > 0 ||
      (user.injuries?.filter((i: string) => i.trim()).length ?? 0) > 0;

    if (hasMedicalRisk) {
      setBlocked(true);
      setBlockedReason(
        'Due to your reported medical conditions or injuries, we cannot safely generate an AI plan. Please consult a certified trainer on our platform for a personalised and safe fitness programme.'
      );
      setLoading(false);
    } else {
      fetchPlan();
    }
  }, [user]);

  const generatePlan = async () => {
    setGenerating(true);
    setErrorMsg(null);
    try {
      const res = await api.post('/plans/generate');
      if (res.data.success) {
        if (res.data.data.blocked) {
          setBlocked(true);
          setBlockedReason(res.data.data.reason);
        } else {
          setPlan(res.data.data);
        }
      }
    } catch (err: any) {
      setErrorMsg(err.response?.data?.message || 'Plan generation failed. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const toggleDay = (day: string) => {
    setExpandedDays((prev) => ({
      ...prev,
      [day]: !prev[day],
    }));
  };

  return (

      <div className="page-wrapper">
        <div className="page-inner">
          {/* Header */}
          <div className="text-center animate-fade-in" style={{ marginBottom: '32px' }}>
            <h1 style={{ marginBottom: '8px' }}>Your AI Plan</h1>
            <p style={{ fontSize: '13px', color: '#8890a8', maxWidth: '420px', margin: '0 auto' }}>
              Evidence-based, structured workout routines and meal plans generated by FitQuanta AI.
            </p>
          </div>

          {errorMsg && (
            <div className="alert-danger" style={{ display: 'flex', justifyContent: 'between', alignItems: 'center', marginBottom: '20px' }}>
              <span>{errorMsg}</span>
              <button 
                onClick={plan ? fetchPlan : generatePlan} 
                className="btn btn-ghost btn-sm"
              >
                Retry
              </button>
            </div>
          )}

          {/* Medical Safety Gate / Blocked Card */}
          {blocked ? (
            <div className="card-fire" style={{ textAlign: 'center', padding: '52px 32px', maxWidth: '600px', margin: '0 auto' }}>
              <p className="section-title" style={{ color: '#ff6b2b', marginBottom: '12px' }}>AI plan unavailable</p>
              <p style={{ fontSize: '13px', color: '#8890a8', maxWidth: '380px', margin: '0 auto 28px', lineHeight: 1.7 }}>{blockedReason}</p>
              <Link href="/trainer" className="btn btn-fire">Browse certified trainers</Link>
            </div>
          ) : loading ? (
            <div className="flex flex-col justify-center items-center py-20 space-y-4">
              <span className="spinner-lg" />
              <p style={{ fontSize: '13px', color: '#8890a8' }}>Loading your plan...</p>
            </div>
          ) : generating ? (
            <div className="flex flex-col justify-center items-center py-20">
              <button disabled className="btn btn-primary btn-lg">
                <span className="spinner" />
                Building your plan...
              </button>
            </div>
          ) : !plan ? (
            // No Plan state
            <div className="card text-center py-12 space-y-6 max-w-lg mx-auto animate-fade-in">
              <h3 className="section-title mb-2">No Plan Generated Yet</h3>
              <p style={{ fontSize: '13px', color: '#8890a8', maxWidth: '320px', margin: '0 auto 20px' }}>
                Ready to transform? Let our custom Llama models craft a dedicated workout and diet plan for you.
              </p>
              <div className="flex justify-center">
                <button
                  onClick={generatePlan}
                  className="btn btn-primary btn-lg"
                >
                  Generate my plan
                </button>
              </div>
            </div>
          ) : (
            // Render Plan
            <div className="space-y-6 animate-fade-in">
              {/* Tab Toggles */}
              <div className="tab-list" style={{ marginBottom: '20px', justifyContent: 'center' }}>
                <button
                  className={activeTab === 'workout' ? 'tab-item tab-item-active' : 'tab-item'}
                  onClick={() => setActiveTab('workout')}
                >
                  Workout Plan
                </button>
                <button
                  className={activeTab === 'diet' ? 'tab-item tab-item-active' : 'tab-item'}
                  onClick={() => setActiveTab('diet')}
                >
                  Diet Plan
                </button>
              </div>

              {/* Tab Contents */}
              <div className="space-y-2">
                {activeTab === 'workout' ? (
                  plan.workoutPlan?.map((dayPlan: any, idx: number) => {
                    const isExpanded = !!expandedDays[dayPlan.day];
                    return (
                      <div key={idx} className="card" style={{ marginBottom: '8px', padding: 0, overflow: 'hidden' }}>
                        <button className="collapse-trigger" onClick={() => toggleDay(dayPlan.day)}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                            <span className="badge-cyan">{dayPlan.day}</span>
                            <span style={{ fontSize: '13px', fontWeight: 600, color: '#eceef4' }}>{dayPlan.focus}</span>
                          </div>
                          <span style={{ color: '#545870', fontSize: '12px', transform: isExpanded ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s ease' }}>▾</span>
                        </button>
                        {isExpanded && (
                          <div style={{ borderTop: '1px solid #22223a', padding: '4px 0 8px' }} className="overflow-x-auto">
                            {!dayPlan.exercises || dayPlan.exercises.length === 0 ? (
                              <p className="text-sm text-text-muted italic px-4 py-2">Rest Day - Recovery and hydration are essential.</p>
                            ) : (
                              <table className="fq-table">
                                <thead>
                                  <tr>
                                    <th>Exercise</th>
                                    <th>Sets</th>
                                    <th>Reps</th>
                                    <th>Rest</th>
                                    <th>Notes</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  {dayPlan.exercises.map((ex: any, j: number) => (
                                    <tr key={j}>
                                      <td style={{ fontWeight: 500 }}>{ex.name}</td>
                                      <td><span className="badge-cyan">{ex.sets}</span></td>
                                      <td style={{ fontFamily: 'var(--font-mono)' }}>{ex.reps}</td>
                                      <td style={{ color: '#8890a8' }}>{ex.rest || '60s'}</td>
                                      <td style={{ color: '#545870', fontSize: '12px' }}>{ex.notes || 'None'}</td>
                                    </tr>
                                  ))}
                                </tbody>
                              </table>
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })
                ) : (
                  plan.dietPlan?.map((dayPlan: any, idx: number) => {
                    const isExpanded = !!expandedDays[dayPlan.day];
                    return (
                      <div key={idx} className="card" style={{ marginBottom: '8px', padding: 0, overflow: 'hidden' }}>
                        <button className="collapse-trigger" onClick={() => toggleDay(dayPlan.day)}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                            <span className="badge-fire">{dayPlan.day}</span>
                            <span style={{ fontSize: '13px', fontWeight: 600, color: '#eceef4' }}>
                              Target Intake: <span className="font-mono text-cyan">{dayPlan.totalCalories || 'N/A'}</span> kcal
                            </span>
                          </div>
                          <span style={{ color: '#545870', fontSize: '12px', transform: isExpanded ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s ease' }}>▾</span>
                        </button>

                        {isExpanded && (
                          <div style={{ borderTop: '1px solid #22223a', padding: '16px' }} className="space-y-4">
                            {!dayPlan.meals || dayPlan.meals.length === 0 ? (
                              <p className="text-sm text-text-muted italic">No meal logged for this day.</p>
                            ) : (
                              dayPlan.meals.map((meal: any, mIdx: number) => (
                                <div key={mIdx} className="bg-raised p-4 rounded-md border border-border/60">
                                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                                    <h5 className="font-semibold text-text-primary text-sm">{meal.name}</h5>
                                    {/* Diet meal macros */}
                                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '5px' }}>
                                      <span className="macro-protein">Protein {meal.protein}g</span>
                                      <span className="macro-carbs">Carbs {meal.carbs}g</span>
                                      <span className="macro-fats">Fats {meal.fats}g</span>
                                      <span className="macro-cal">{meal.calories} kcal</span>
                                    </div>
                                  </div>
                                  <p style={{ fontSize: '12px', color: '#8890a8', marginTop: '8px' }}>
                                    <strong style={{ color: '#eceef4' }}>Ingredients: </strong>
                                    {Array.isArray(meal.foods) ? meal.foods.join(', ') : meal.foods}
                                  </p>
                                </div>
                              ))
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })
                )}
              </div>

              {/* Re-generate CTA */}
              <div className="text-center pt-6">
                <button
                  type="button"
                  onClick={generatePlan}
                  className="btn btn-ghost btn-sm"
                >
                  Re-generate AI Plan
                </button>
              </div>
            </div>
          )}
      </div>
    </div>
  );
}

export default function PlansPage() {
  const { user } = useSelector((state: RootState) => state.auth);

  return (
    <ProtectedRoute>
      {user && <PlansContent user={user} />}
    </ProtectedRoute>
  );
}

