'use client';

import React, { useEffect, useState } from 'react';
import ProtectedRoute from '@/components/ProtectedRoute';
import { useSelector } from 'react-redux';
import { RootState } from '@/redux/store';
import Link from 'next/link';
import api from '@/lib/axiosInstance';
import type { IPlan } from '@/types/plan';

export default function PlansPage() {
  const { user } = useSelector((state: RootState) => state.auth);
  const [activeTab, setActiveTab] = useState<'workout' | 'diet'>('workout');
  const [plan, setPlan] = useState<any | null>(null);
  const [blocked, setBlocked] = useState(false);
  const [blockedReason, setBlockedReason] = useState('');
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [expandedDays, setExpandedDays] = useState<Record<string, boolean>>({});

  const fetchPlan = async () => {
    setLoading(true);
    setErrorMsg(null);
    try {
      const res = await api.get('/plans');
      if (res.data.success && res.data.data) {
        setPlan(res.data.data);
      }
    } catch (err: any) {
      setErrorMsg(err.response?.data?.message || 'Failed to load fitness plan.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (user) {
      const hasMedicalRisk =
        (user.medicalConditions?.filter((c) => c.trim()).length ?? 0) > 0 ||
        (user.injuries?.filter((i) => i.trim()).length ?? 0) > 0;

      if (hasMedicalRisk) {
        setBlocked(true);
        setBlockedReason(
          'Due to your reported medical conditions or injuries, we cannot safely generate an AI plan. Please consult a certified trainer on our platform for a personalised and safe fitness programme.'
        );
        setLoading(false);
      } else {
        fetchPlan();
      }
    }
  }, [user]);

  const generatePlan = async () => {
    setGenerating(true);
    setErrorMsg(null);
    try {
      const res = await api.post('/plans/generate');
      if (res.data.success) {
        if (res.data.data.blocked) {
          setBlocked(true);
          setBlockedReason(res.data.data.reason);
        } else {
          setPlan(res.data.data);
        }
      }
    } catch (err: any) {
      setErrorMsg(err.response?.data?.message || 'Plan generation failed. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const toggleDay = (day: string) => {
    setExpandedDays((prev) => ({
      ...prev,
      [day]: !prev[day],
    }));
  };

  if (!user) return null;

  return (
    <ProtectedRoute>
      <div className="min-h-[85vh] bg-[#0a0a0f] py-10 px-6 font-body text-[#e2e8f0]">
        <div className="max-w-4xl mx-auto space-y-8">
          <div className="text-center">
            <h1 className="font-display text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-[#00d4ff] to-[#ff6b35] mb-2 drop-shadow-[0_0_10px_rgba(0,212,255,0.2)]">
              Your AI Fitness & Diet Plan
            </h1>
            <p className="text-sm text-[#94a3b8]">
              Evidence-based, structured workout routines and meal plans generated by FitQuanta AI.
            </p>
          </div>

          {errorMsg && (
            <div className="bg-red-500/10 border border-red-500 text-red-500 p-4 rounded-xl text-sm flex justify-between items-center">
              <span>{errorMsg}</span>
              <button 
                onClick={plan ? fetchPlan : generatePlan} 
                className="px-3 py-1 bg-red-500 text-white rounded-lg text-xs font-bold hover:bg-red-600 transition-colors"
              >
                Retry
              </button>
            </div>
          )}

          {/* Medical Safety Gate / Blocked Card */}
          {blocked ? (
            <div className="border border-orange-500/40 bg-orange-500/5 rounded-2xl p-8 text-center space-y-6 max-w-2xl mx-auto shadow-[0_0_20px_rgba(255,107,53,0.1)]">
              <div className="text-4xl text-[#ff6b35] animate-bounce">⚠️</div>
              <div className="space-y-2">
                <h3 className="font-display text-2xl font-bold text-orange-500">AI Plan Unavailable</h3>
                <p className="text-sm text-[#e2e8f0] leading-relaxed">
                  {blockedReason}
                </p>
                <p className="text-xs text-[#94a3b8] leading-relaxed pt-2">
                  Your safety is our priority. Our certified trainers are equipped to design a plan that works safely around your specific needs.
                </p>
              </div>
              <div>
                <Link href="/trainer" className="inline-block px-6 py-3 bg-orange-500 text-[#0a0a0f] font-bold rounded-xl hover:bg-orange-600 transition-all shadow-[0_0_15px_rgba(255,107,53,0.3)]">
                  Browse Certified Trainers
                </Link>
              </div>
            </div>
          ) : loading ? (
            <div className="flex flex-col justify-center items-center py-20 space-y-4">
              <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-[#00d4ff] shadow-[0_0_15px_rgba(0,212,255,0.4)]"></div>
              <p className="text-[#94a3b8] text-sm font-semibold">Loading your plan...</p>
            </div>
          ) : generating ? (
            <div className="flex flex-col justify-center items-center py-20 space-y-4">
              {/* Spinning custom icon representation */}
              <div className="animate-spin rounded-full h-16 w-16 border-t-4 border-b-4 border-t-[#00d4ff] border-b-[#ff6b35] shadow-[0_0_20px_rgba(0,212,255,0.4)]"></div>
              <p className="text-[#00d4ff] font-display text-lg font-bold animate-pulse">FitQuanta AI is building your plan...</p>
            </div>
          ) : !plan ? (
            // No Plan generated state
            <div className="bg-[#12121a] p-8 rounded-2xl border border-[#1e1e2e] text-center space-y-6 py-12">
              <h3 className="font-display text-xl font-bold">No Plan Generated Yet</h3>
              <p className="text-sm text-[#94a3b8] max-w-md mx-auto">
                Ready to transform? Let our custom Llama 3 models craft a dedicated workout and diet plan for you.
              </p>
              <button
                onClick={generatePlan}
                className="px-6 py-3 bg-[#00d4ff] text-[#0a0a0f] rounded-xl font-bold hover:bg-[#0099bb] shadow-[0_0_15px_rgba(0,212,255,0.3)] transition-all"
              >
                Generate My Plan
              </button>
            </div>
          ) : (
            // Render Plan
            <div className="space-y-6">
              {/* Tab Toggles: Pill style with cyan underline */}
              <div className="flex justify-center bg-[#12121a] p-1.5 rounded-xl border border-[#1e1e2e] max-w-xs mx-auto">
                <button
                  onClick={() => setActiveTab('workout')}
                  className={`flex-1 py-2 text-sm font-bold rounded-lg transition-all relative ${
                    activeTab === 'workout'
                      ? 'text-[#00d4ff]'
                      : 'text-[#94a3b8] hover:text-[#e2e8f0]'
                  }`}
                >
                  Workout Plan
                  {activeTab === 'workout' && (
                    <span className="absolute bottom-0 left-1/4 right-1/4 h-[2px] bg-[#00d4ff] shadow-[0_0_8px_rgba(0,212,255,0.8)]" />
                  )}
                </button>
                <button
                  onClick={() => setActiveTab('diet')}
                  className={`flex-1 py-2 text-sm font-bold rounded-lg transition-all relative ${
                    activeTab === 'diet'
                      ? 'text-[#00d4ff]'
                      : 'text-[#94a3b8] hover:text-[#e2e8f0]'
                  }`}
                >
                  Diet Plan
                  {activeTab === 'diet' && (
                    <span className="absolute bottom-0 left-1/4 right-1/4 h-[2px] bg-[#00d4ff] shadow-[0_0_8px_rgba(0,212,255,0.8)]" />
                  )}
                </button>
              </div>

              {/* Tab Contents */}
              <div className="space-y-4">
                {activeTab === 'workout' ? (
                  plan.workoutPlan?.map((dayPlan: any, idx: number) => {
                    const isExpanded = !!expandedDays[dayPlan.day];
                    return (
                      <div
                        key={idx}
                        className="bg-[#12121a] border border-[#1e1e2e] rounded-2xl overflow-hidden shadow-[0_4px_15px_rgba(0,0,0,0.3)] transition-all"
                      >
                        <button
                          onClick={() => toggleDay(dayPlan.day)}
                          className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-[#1a1a2e]/40 transition-colors"
                        >
                          <div>
                            <h4 className="font-display font-extrabold text-lg text-[#00d4ff]">
                              {dayPlan.day}
                            </h4>
                            <span className="text-xs text-[#94a3b8] mt-1 block font-semibold">
                              Focus: <span className="text-[#ff6b35]">{dayPlan.focus || 'Rest/Recovery'}</span>
                            </span>
                          </div>
                          <span className="text-[#94a3b8] text-sm">
                            {isExpanded ? 'Hide Details ▲' : 'Show Details ▼'}
                          </span>
                        </button>
                        
                        {isExpanded && (
                          <div className="px-6 pb-6 border-t border-[#1e1e2e] pt-4 bg-[#0a0a0f]/40 overflow-x-auto">
                            {!dayPlan.exercises || dayPlan.exercises.length === 0 ? (
                              <p className="text-sm text-[#94a3b8] italic">Rest Day - Recovery and hydration are essential.</p>
                            ) : (
                              <table className="w-full text-left text-sm border-collapse min-w-[500px]">
                                <thead>
                                  <tr className="border-b border-[#1e1e2e] text-[#94a3b8] font-bold text-xs uppercase tracking-wider">
                                    <th className="pb-3 pr-4">Exercise</th>
                                    <th className="pb-3 px-4">Sets</th>
                                    <th className="pb-3 px-4">Reps</th>
                                    <th className="pb-3 px-4">Rest</th>
                                    <th className="pb-3 pl-4">Notes</th>
                                  </tr>
                                </thead>
                                <tbody className="divide-y divide-[#1e1e2e]/50">
                                  {dayPlan.exercises.map((ex: any, eIdx: number) => (
                                    <tr key={eIdx} className="hover:bg-[#1e1e2e]/20 transition-colors">
                                      <td className="py-3 pr-4 font-bold text-[#e2e8f0]">{ex.name}</td>
                                      <td className="py-3 px-4">
                                        <span className="px-2 py-0.5 bg-[#00d4ff]/10 text-[#00d4ff] text-xs font-bold rounded-lg">
                                          {ex.sets}
                                        </span>
                                      </td>
                                      <td className="py-3 px-4 text-[#e2e8f0]">{ex.reps}</td>
                                      <td className="py-3 px-4 text-[#94a3b8]">{ex.rest || '60s'}</td>
                                      <td className="py-3 pl-4 text-xs text-[#94a3b8] italic max-w-xs truncate" title={ex.notes}>
                                        {ex.notes || 'None'}
                                      </td>
                                    </tr>
                                  ))}
                                </tbody>
                              </table>
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })
                ) : (
                  plan.dietPlan?.map((dayPlan: any, idx: number) => {
                    const isExpanded = !!expandedDays[dayPlan.day];
                    return (
                      <div
                        key={idx}
                        className="bg-[#12121a] border border-[#1e1e2e] rounded-2xl overflow-hidden shadow-[0_4px_15px_rgba(0,0,0,0.3)] transition-all"
                      >
                        <button
                          onClick={() => toggleDay(dayPlan.day)}
                          className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-[#1a1a2e]/40 transition-colors"
                        >
                          <div>
                            <h4 className="font-display font-extrabold text-lg text-[#ff6b35]">
                              {dayPlan.day}
                            </h4>
                            <span className="text-xs text-[#94a3b8] mt-1 block font-semibold">
                              Target Intake: <span className="text-[#00d4ff]">{dayPlan.totalCalories || 'N/A'} kcal</span>
                            </span>
                          </div>
                          <span className="text-[#94a3b8] text-sm">
                            {isExpanded ? 'Hide Meals ▲' : 'Show Meals ▼'}
                          </span>
                        </button>

                        {isExpanded && (
                          <div className="px-6 pb-6 border-t border-[#1e1e2e] pt-4 bg-[#0a0a0f]/40 space-y-4">
                            {!dayPlan.meals || dayPlan.meals.length === 0 ? (
                              <p className="text-sm text-[#94a3b8] italic">No meal logged for this day.</p>
                            ) : (
                              dayPlan.meals.map((meal: any, mIdx: number) => (
                                <div key={mIdx} className="bg-[#12121a] p-5 rounded-xl border border-[#1e1e2e]/60 space-y-3 shadow-inner">
                                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                                    <h5 className="font-bold text-base text-[#e2e8f0]">{meal.name}</h5>
                                    <div className="flex flex-wrap gap-2">
                                      {/* protein: cyan */}
                                      <span className="px-2 py-0.5 bg-[#00d4ff]/10 text-[#00d4ff] border border-[#00d4ff]/20 text-[10px] font-bold rounded-full">
                                        Protein: {meal.protein}g
                                      </span>
                                      {/* carbs: orange */}
                                      <span className="px-2 py-0.5 bg-[#ff6b35]/10 text-[#ff6b35] border border-[#ff6b35]/20 text-[10px] font-bold rounded-full">
                                        Carbs: {meal.carbs}g
                                      </span>
                                      {/* fats: yellow */}
                                      <span className="px-2 py-0.5 bg-yellow-400/10 text-yellow-400 border border-yellow-400/20 text-[10px] font-bold rounded-full">
                                        Fats: {meal.fats}g
                                      </span>
                                      {/* calories: white/muted */}
                                      <span className="px-2 py-0.5 bg-white/5 text-[#e2e8f0] border border-white/10 text-[10px] font-bold rounded-full">
                                        Cal: {meal.calories} kcal
                                      </span>
                                    </div>
                                  </div>
                                  <p className="text-xs text-[#94a3b8] leading-relaxed">
                                    <span className="font-bold text-[#e2e8f0]">Ingredients: </span>
                                    {Array.isArray(meal.foods) ? meal.foods.join(', ') : meal.foods}
                                  </p>
                                </div>
                              ))
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })
                )}
              </div>

              {/* Re-generate CTA */}
              <div className="text-center pt-6">
                <button
                  onClick={generatePlan}
                  className="px-6 py-3 border border-[#00d4ff] text-[#00d4ff] hover:bg-[#00d4ff]/15 rounded-xl font-bold text-sm transition-all shadow-[0_0_10px_rgba(0,212,255,0.15)]"
                >
                  Re-generate AI Plan
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </ProtectedRoute>
  );
}
