'use client';

import React, { useEffect, useState } from 'react';
import ProtectedRoute from '@/components/ProtectedRoute';
import { useSelector } from 'react-redux';
import { RootState } from '@/redux/store';
import Link from 'next/link';
import api from '@/lib/axiosInstance';

export default function PlansPage() {
  const { user } = useSelector((state: RootState) => state.auth);
  const [activeTab, setActiveTab] = useState<'workout' | 'diet'>('workout');
  const [plan, setPlan] = useState<any | null>(null);
  const [blocked, setBlocked] = useState(false);
  const [blockedReason, setBlockedReason] = useState('');
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [expandedDays, setExpandedDays] = useState<Record<string, boolean>>({});

  const fetchPlan = async () => {
    setLoading(true);
    setErrorMsg(null);
    try {
      const res = await api.get('/plans');
      if (res.data.success && res.data.data) {
        setPlan(res.data.data);
      }
    } catch (err: any) {
      setErrorMsg(err.response?.data?.message || 'Failed to load fitness plan.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (user) {
      const hasMedicalRisk =
        (user.medicalConditions?.filter((c) => c.trim()).length ?? 0) > 0 ||
        (user.injuries?.filter((i) => i.trim()).length ?? 0) > 0;

      if (hasMedicalRisk) {
        setBlocked(true);
        setBlockedReason(
          'Due to your reported medical conditions or injuries, we cannot safely generate an AI plan. Please consult a certified trainer on our platform for a personalised and safe fitness programme.'
        );
        setLoading(false);
      } else {
        fetchPlan();
      }
    }
  }, [user]);

  const generatePlan = async () => {
    setGenerating(true);
    setErrorMsg(null);
    try {
      const res = await api.post('/plans/generate');
      if (res.data.success) {
        if (res.data.data.blocked) {
          setBlocked(true);
          setBlockedReason(res.data.data.reason);
        } else {
          setPlan(res.data.data);
        }
      }
    } catch (err: any) {
      setErrorMsg(err.response?.data?.message || 'Plan generation failed. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const toggleDay = (day: string) => {
    setExpandedDays((prev) => ({
      ...prev,
      [day]: !prev[day],
    }));
  };

  if (!user) return null;

  return (
    <ProtectedRoute>
      <div className="page-wrapper">
        <div className="page-content space-y-8">
          {/* Header */}
          <div className="text-center animate-fade-in">
            <h1 className="page-title text-cyan mb-2">Your AI Plan</h1>
            <p className="text-sm text-text-muted max-w-md mx-auto">
              Evidence-based, structured workout routines and meal plans generated by FitQuanta AI.
            </p>
          </div>

          {errorMsg && (
            <div className="alert-danger flex justify-between items-center animate-fade-in">
              <span>{errorMsg}</span>
              <button 
                onClick={plan ? fetchPlan : generatePlan} 
                className="btn-secondary text-xs py-1 px-3"
              >
                Retry
              </button>
            </div>
          )}

          {/* Medical Safety Gate / Blocked Card */}
          {blocked ? (
            <div className="card border-orange/30 bg-orange/5 text-center py-12 px-6 max-w-2xl mx-auto animate-fade-in">
              <div className="text-5xl mb-4">⚠️</div>
              <h2 className="font-display text-xl font-bold text-orange uppercase tracking-wider mb-3">
                AI Plan Unavailable
              </h2>
              <p className="text-text-muted text-sm max-w-md mx-auto mb-6 leading-relaxed">
                {blockedReason}
              </p>
              <div className="flex justify-center">
                <Link href="/trainer" className="btn-danger inline-block">Browse certified trainers</Link>
              </div>
            </div>
          ) : loading ? (
            <div className="flex flex-col justify-center items-center py-20 space-y-4">
              <span className="spinner-lg" />
              <p className="text-text-muted text-sm font-semibold">Loading your plan...</p>
            </div>
          ) : generating ? (
            <div className="flex flex-col justify-center items-center py-20 space-y-4">
              <span className="spinner-lg" />
              <p className="text-cyan font-display text-lg font-bold animate-pulse-cyan">FitQuanta AI is building your plan...</p>
            </div>
          ) : !plan ? (
            // No Plan state
            <div className="card text-center py-12 space-y-6 max-w-lg mx-auto animate-fade-in">
              <h3 className="card-title text-lg">No Plan Generated Yet</h3>
              <p className="text-sm text-text-muted max-w-sm mx-auto">
                Ready to transform? Let our custom Llama models craft a dedicated workout and diet plan for you.
              </p>
              <div className="flex justify-center">
                <button
                  onClick={generatePlan}
                  className="btn-primary px-8 py-3 text-base"
                >
                  Generate my plan
                </button>
              </div>
            </div>
          ) : (
            // Render Plan
            <div className="space-y-6 animate-fade-in">
              {/* Tab Toggles */}
              <div className="tab-bar max-w-xs mx-auto">
                <button
                  onClick={() => setActiveTab('workout')}
                  className={activeTab === 'workout' ? 'tab-item-active' : 'tab-item'}
                >
                  Workout Plan
                </button>
                <button
                  onClick={() => setActiveTab('diet')}
                  className={activeTab === 'diet' ? 'tab-item-active' : 'tab-item'}
                >
                  Diet Plan
                </button>
              </div>

              {/* Tab Contents */}
              <div className="space-y-3">
                {activeTab === 'workout' ? (
                  plan.workoutPlan?.map((dayPlan: any, idx: number) => {
                    const isExpanded = !!expandedDays[dayPlan.day];
                    return (
                      <div key={idx} className="card p-0 overflow-hidden">
                        <button
                          onClick={() => toggleDay(dayPlan.day)}
                          className="collapsible-header"
                        >
                          <div className="flex items-center gap-3">
                            <span className="badge-cyan text-xs font-mono">{dayPlan.day}</span>
                            <span className="card-title text-sm">{dayPlan.focus}</span>
                          </div>
                          <span className={`text-text-muted transition-transform duration-200 ${isExpanded ? 'rotate-180' : ''}`}>▾</span>
                        </button>
                        
                        {isExpanded && (
                          <div className="px-6 pb-6 border-t border-border/30 pt-4 bg-[#0a0a12]/20 overflow-x-auto">
                            {!dayPlan.exercises || dayPlan.exercises.length === 0 ? (
                              <p className="text-sm text-text-muted italic">Rest Day - Recovery and hydration are essential.</p>
                            ) : (
                              <table className="fq-table">
                                <thead>
                                  <tr>
                                    <th>Exercise</th>
                                    <th>Sets</th>
                                    <th>Reps</th>
                                    <th>Rest</th>
                                    <th>Notes</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  {dayPlan.exercises.map((ex: any, eIdx: number) => (
                                    <tr key={eIdx}>
                                      <td className="font-medium text-text-primary">{ex.name}</td>
                                      <td>
                                        <span className="badge-cyan font-mono text-[11px]">
                                          {ex.sets}
                                        </span>
                                      </td>
                                      <td className="font-mono text-text-primary">{ex.reps}</td>
                                      <td className="text-text-muted font-mono">{ex.rest || '60s'}</td>
                                      <td className="text-text-hint text-xs italic max-w-xs truncate" title={ex.notes}>
                                        {ex.notes || 'None'}
                                      </td>
                                    </tr>
                                  ))}
                                </tbody>
                              </table>
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })
                ) : (
                  plan.dietPlan?.map((dayPlan: any, idx: number) => {
                    const isExpanded = !!expandedDays[dayPlan.day];
                    return (
                      <div key={idx} className="card p-0 overflow-hidden">
                        <button
                          onClick={() => toggleDay(dayPlan.day)}
                          className="collapsible-header"
                        >
                          <div className="flex items-center gap-3">
                            <span className="badge-orange text-xs font-mono">{dayPlan.day}</span>
                            <span className="card-title text-sm">
                              Target Intake: <span className="font-mono text-cyan">{dayPlan.totalCalories || 'N/A'}</span> kcal
                            </span>
                          </div>
                          <span className={`text-text-muted transition-transform duration-200 ${isExpanded ? 'rotate-180' : ''}`}>▾</span>
                        </button>

                        {isExpanded && (
                          <div className="px-6 pb-6 border-t border-border/30 pt-4 bg-[#0a0a12]/20 space-y-4">
                            {!dayPlan.meals || dayPlan.meals.length === 0 ? (
                              <p className="text-sm text-text-muted italic">No meal logged for this day.</p>
                            ) : (
                              dayPlan.meals.map((meal: any, mIdx: number) => (
                                <div key={mIdx} className="bg-raised p-5 rounded-md border border-border/60 space-y-3 shadow-inner">
                                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                                    <h5 className="font-semibold text-text-primary text-sm">{meal.name}</h5>
                                    <div className="flex flex-wrap gap-2">
                                      <span className="macro-protein">Protein: <span className="font-mono">{meal.protein}g</span></span>
                                      <span className="macro-carbs">Carbs: <span className="font-mono">{meal.carbs}g</span></span>
                                      <span className="macro-fats">Fats: <span className="font-mono">{meal.fats}g</span></span>
                                      <span className="macro-cal">Cal: <span className="font-mono">{meal.calories} kcal</span></span>
                                    </div>
                                  </div>
                                  <p className="text-xs text-text-muted leading-relaxed">
                                    <span className="font-bold text-text-primary">Ingredients: </span>
                                    {Array.isArray(meal.foods) ? meal.foods.join(', ') : meal.foods}
                                  </p>
                                </div>
                              ))
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })
                )}
              </div>

              {/* Re-generate CTA */}
              <div className="text-center pt-6">
                <button
                  onClick={generatePlan}
                  className="btn-secondary text-sm"
                >
                  Re-generate AI Plan
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </ProtectedRoute>
  );
}
